package com.br.luggycar.api.enums.rent;

public enum RestrictionType {
    VEHICLE_DAMAGED,
    VEHICLE_STOLEN,
    VEHICLE_DESTROYED,
    VEHICLE_DETAINED,
    OPTIONAL_ITEM_DAMAGED,
    OPTIONAL_ITEM_LOST_STOLEN,
    OPTIONAL_ITEM_DESTROYED,
    OPTIONAL_ITEM_DETAINED
}

